// modules/vue/nuxt_html_rendring/pages/index.vue
<template>
    <v-runtime-template :template="rawHtml" />
</template>

<script>
import MyStrong from '../components/MyStrong.vue'
import VRuntimeTemplate from 'v-runtime-template'

export default {
    components: {
        MyStrong,
        VRuntimeTemplate
    },
    asyncData() {
        try {
            const filename = 'hoge/aa.html'
            var str = require(`../contents/${filename}`)
            return {
                rawHtml: `<div>${str.default}</div>`
            }
        } catch(e) {
            console.log(e)
            return {
                rawHtml: `<div>An error occurs</div>`
            }
        }
    }
}
</script>

// next_html_rendering/pages/index.jsx
import MyStrong from '../components/MyStrong';
import React from 'react';
import JsxParser from "react-jsx-parser";

export const getStaticProps = async () => {
    const filename = 'hoge/aa.html'
    const raw = await require(`../contents/${filename}`);
    console.log(raw.default);
    return { props: { html: raw.default }};
};

export default ({html}) => {
    return (
//        <div>aa</div>
        <div>
        <JsxParser components={{MyStrong}} jsx={html} />
        </div>
    );
};
