// modules/vue/vue/ensyu2/src/App.vue
<template>
	<button @click="onClick()">count!!</button>
  <div v-if="count===0">The button has not pushed!!</div>
  <div v-else>Count:{{count}}</div>
</template>

<script>

export default {
	data() {
		return {
			count: 0
		};
	},
	methods: {
		onClick() {
			this.count = this.count + 1;
		}
	}
}
</script>

// react_component/ensyu4/src/App.js
import React, { Component } from 'react';

export default class extends Component {
    constructor() {
        super();
        this.state = {
            counter: 0,
        };
        this.count = this.count.bind(this);
    }

    count(e) {
        this.setState((state) => {
            return {
                counter: state.counter + 1,
            }
        });
    }

    get text() {
        if (this.state.counter === 0) {
            return 'The button has not pushed!!'
        } else {
            return `Count: ${this.state.counter}`;
        }
    }

    render() {
        return (
            <div>
                <button onClick={this.count}>Counter</button>
                <p> { this.text } </p>
            </div>
        );
    }
}
