// modules/react/next/ensyu1/pages/index.jsx

function convertDate(date) {
    return `${date.getFullYear()}/${date.getMonth() + 1}/${date.getDate()} ${date.getHours()}:${date.getMinutes()}:${date.getMinutes()}`;
}

export const getStaticProps = async (ctx) => {
    console.log(ctx);
    const now = new Date();
    return { props: { initialDate: convertDate(now)} };
}

export default (props) => {
    const now = convertDate(new Date());
    return (<div>
        <div>initialDate: {props.initialDate}</div>
        <div>date: {now}</div>
    </div>);
};

// modules/vue/nuxt/ensyu4/pages/index.vue
<template>
    <div>
        <div>asyncData: {{asyncCurrentTime}}</div>
        <div>data: {{currentTime}}</div>
        <div>computed: {{computedCurrentTime}}</div>
    </div>
</template>

<script>
export default {
    asyncData() {
        const now = new Date()
        return {
            asyncCurrentTime: `${now.getFullYear()}/${now.getMonth() + 1}/${now.getDate()} ${now.getHours()}:${now.getMinutes()}:${now.getMinutes()}`
        }
    },
    data() {
        const now = new Date()
        return {
            currentTime: `${now.getFullYear()}/${now.getMonth() + 1}/${now.getDate()} ${now.getHours()}:${now.getMinutes()}:${now.getMinutes()}`
        }
    },
    computed: {
        computedCurrentTime: function() {
            const now = new Date()
            return `${now.getFullYear()}/${now.getMonth() + 1}/${now.getDate()} ${now.getHours()}:${now.getMinutes()}:${now.getMinutes()}`
        }
    }
}
</script>
